version: "3"
services:
  mongodb:
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express:0.49
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_ROOT_USERNAME:-root}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_ROOT_PWD:-password}
      ME_CONFIG_MONGODB_SERVER: mongodb
    healthcheck:
      test: ["CMD", "curl", "localhost:8081"]
      interval: 30s
      timeout: 10s
      retries: 3
