version: "3"
services:
  mongodb:
    env_file:
      - multicast.env
    restart: "always"
    image: mongo:4.0
    healthcheck:
      test: ["CMD", "mongo", "--quiet", "localhost/test", "--eval", "'quit(db.runCommand({ ping: 1 }).ok ? 0 : 1)';"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - mongo-data:/data/db
      - mongo-backup:/opt/backup

volumes:
  mongo-data:
  mongo-backup:
