version: "3"
services:
  multicast:
    env_file:
      - multicast.env
    restart: "always"
    image: ${MULTICAST_IMAGE:-multicast:local}
    ports:
      - 3944:3944
    environment:
      MONGO_HOST: mongodb
    healthcheck:
      test: ["CMD", "curl", "localhost:3944"]
      interval: 30s
      timeout: 10s
      retries: 3
